environment:
  nodejs_version: "10"

os: unstable

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run test
  - npm run package

artifacts:
  - path: dist/*.exe
    name: SetupExe

  - path: dist/*.zip
    name: ProductZip

deploy:
  provider: GitHub
  auth_token:
    secure: ODr3CTy3FPAl9ed7WuVwdhdK+KSy8fdE3ndTZGDzqYTo7T1fwvcwLKZ1QZmxByk3
  draft: true
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true

cache:
  - binaries
  - node_modules

build: off
